# SearXNG Configuration

general:
  debug: false
  instance_name: "OSINT SearXNG"
  contact_url: false
  enable_stats: false
  enable_outgoing_cookies: false
  outgoing_useragent: "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "ultrasecretkey"
  base_url: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block

ui:
  static_use_hash: false
  default_theme: simple
  default_locale: ""
  theme_args:
    simple_style: dark
  center_alignment: false
  results_on_new_tab: false
  search_on_category_select: true
  infinite_scroll: false

engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false
    
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
    
  - name: github
    engine: github
    shortcut: gh
    disabled: false
    
  - name: reddit
    engine: reddit
    shortcut: re
    disabled: false

redis:
  url: redis://redis:6379/0