global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'beef'
    static_configs:
      - targets: ['beef:3000']

  - job_name: 'searxng'
    static_configs:
      - targets: ['searxng:8080']

  - job_name: 'localai'
    static_configs:
      - targets: ['localai:8080']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'netdata'
    static_configs:
      - targets: ['netdata:19999']