# Default values for CloudCurio Helm chart

# Global configuration
global:
  imageRegistry: ""
  imageTag: "2.2.0"
  imagePullSecrets: []
  storageClass: ""
  namespace: "cloudcurio"

# CloudCurio MCP Server configuration
mcpServer:
  enabled: true
  replicaCount: 1
  image:
    repository: cbwinslow/cloudcurio-mcp
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Configuration Editor configuration
configEditor:
  enabled: true
  replicaCount: 1
  image:
    repository: cbwinslow/cloudcurio-config-editor
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# Ollama configuration
ollama:
  enabled: true
  replicaCount: 1
  image:
    repository: ollama/ollama
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 11434
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 1000m
      memory: 2Gi
      nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu.present: "true"
  persistence:
    enabled: true
    size: 50Gi
    accessModes:
      - ReadWriteOnce

# LiteLLM configuration
litellm:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/berriai/litellm
    tag: "main-latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# Open WebUI configuration
openWebUI:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "main"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

# PostgreSQL database configuration
postgresql:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  auth:
    username: "postgres"
    password: "password"
    database: "cloudcurio"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  primary:
    persistence:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce

# Redis configuration
redis:
  enabled: true
  replicaCount: 1
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  master:
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce

# Monitoring stack configuration
monitoring:
  enabled: true
  
  # Prometheus configuration
  prometheus:
    enabled: true
    replicaCount: 1
    image:
      repository: prom/prometheus
      tag: "v2.45.0"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9090
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    retention: "15d"
    persistence:
      enabled: true
      size: 50Gi
      accessModes:
        - ReadWriteOnce
  
  # Grafana configuration
  grafana:
    enabled: true
    replicaCount: 1
    image:
      repository: grafana/grafana
      tag: "10.0.3"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3000
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    adminUser: "admin"
    adminPassword: "admin"
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
  
  # Loki configuration
  loki:
    enabled: true
    replicaCount: 1
    image:
      repository: grafana/loki
      tag: "2.8.3"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3100
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      size: 50Gi
      accessModes:
        - ReadWriteOnce

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: cloudcurio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

# Affinity rules
affinity: {}

# Node selector rules
nodeSelector: {}

# Tolerations
tolerations: []