# Traefik Configuration

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    constraints: "Label(`traefik.enable`, `true`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true

# Certificates configuration
certificatesResolvers:
  myresolver:
    acme:
      email: admin@osint.local
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

# Log configuration
log:
  level: INFO
  filePath: /var/log/traefik.log

# Access log configuration
accessLog:
  filePath: /var/log/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200"
      - "300-302"
      - "400-499"
      - "500-599"