# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'osint-monitor'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'beef'
    static_configs:
      - targets: ['beef:3000']

  - job_name: 'searxng'
    static_configs:
      - targets: ['searxng:8080']

  - job_name: 'localai'
    static_configs:
      - targets: ['localai:8080']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'openwebui'
    static_configs:
      - targets: ['openwebui:8080']

  - job_name: 'localrecall'
    static_configs:
      - targets: ['localrecall:8082']

  - job_name: 'flowise'
    static_configs:
      - targets: ['flowise:3002']

  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:3004']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'netdata'
    static_configs:
      - targets: ['netdata:19999']

  - job_name: 'portainer'
    static_configs:
      - targets: ['portainer:9000']

  - job_name: 'kali-osint'
    static_configs:
      - targets: ['kali-osint:80']

  - job_name: 'blackarch-osint'
    static_configs:
      - targets: ['blackarch-osint:80']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

remote_write:
  - url: http://loki:3100/loki/api/v1/push