---
- name: Download Loki
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.9.8/loki-linux-amd64.zip
    dest: /tmp/loki.zip
  when: install_loki

- name: Unzip Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
  when: install_loki

- name: Create Loki config
  copy:
    content: |
      auth_enabled: false
      server:
        http_listen_port: 3100
      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 1h
        max_chunk_age: 1h
        chunk_target_size: 1048576
        chunk_retain_period: 30s
        max_transfer_retries: 0
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /tmp/loki/boltdb-shipper-active
          cache_location: /tmp/loki/boltdb-shipper-cache
          shared_store: filesystem
        filesystem:
          directory: /tmp/loki/chunks
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      compactor:
        working_directory: /tmp/loki/compactor
        shared_store: filesystem
        compaction_interval: 10m
        retention_enabled: false
    dest: /etc/loki/local-config.yaml
  become: yes
  when: install_loki

- name: Create Loki systemd service
  copy:
    content: |
      [Unit]
      Description=Loki
      After=network.target

      [Service]
      User=loki
      ExecStart=/usr/local/bin/loki -config.file=/etc/loki/local-config.yaml
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/loki.service
  become: yes
  when: install_loki

- name: Start Loki
  systemd:
    name: loki
    state: started
    enabled: yes
  become: yes
  when: install_loki
