name: Backup Platform

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create backup
        run: |
          echo "Creating backup of OSINT Platform..."
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          BACKUP_NAME="osint-platform-backup-$TIMESTAMP"
          
          # Create backup directory
          mkdir -p backups/$BACKUP_NAME
          
          # Backup configuration files
          cp -r config backups/$BACKUP_NAME/
          cp -r traefik backups/$BACKUP_NAME/
          cp -r kong backups/$BACKUP_NAME/
          cp -r searxng backups/$BACKUP_NAME/
          cp -r prometheus backups/$BACKUP_NAME/
          
          # Create backup archive
          tar -czf backups/$BACKUP_NAME.tar.gz -C backups $BACKUP_NAME
          
          # Clean up temporary directory
          rm -rf backups/$BACKUP_NAME

      - name: Upload backup to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backups/*.tar.gz
          tag: backup-${{ github.run_number }}
          overwrite: true
          body: "Automated backup of OSINT Platform"

      - name: Cleanup old backups
        run: |
          # Keep only the last 7 backups
          cd backups
          ls -t *.tar.gz | tail -n +8 | xargs -r rm