name: CloudCurio CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r crew/requirements.txt
        pip install -r config_editor/requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pip install pytest
        # Run tests if available
        # pytest

  build-mcp-server:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push MCP Server Docker image
      run: |
        # This would build and push the Docker image
        echo "Building MCP Server image..."
        # docker build -f Dockerfile.mcp -t cbwinslow/cloudcurio-mcp:latest .
        # docker push cbwinslow/cloudcurio-mcp:latest

  build-config-editor:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push Config Editor Docker image
      run: |
        # This would build and push the Docker image
        echo "Building Config Editor image..."
        # docker build -f Dockerfile.config-editor -t cbwinslow/cloudcurio-config-editor:latest .
        # docker push cbwinslow/cloudcurio-config-editor:latest