name: Code Quality Checks

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  schedule:
    # Run weekly on Mondays
    - cron: '0 9 * * 1'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r crew/requirements.txt
        pip install -r config_editor/requirements.txt
        pip install -r ai_tools/requirements.txt
        pip install -r feature_tracking/requirements.txt
        pip install flake8 black mypy pylint
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with Black
      run: |
        black --check .
    
    - name: Type checking with MyPy
      run: |
        mypy --package ai_tools || echo "MyPy completed with warnings"
        mypy --package crew || echo "MyPy completed with warnings"
        mypy --package sysmon || echo "MyPy completed with warnings"
        mypy --package config_editor || echo "MyPy completed with warnings"
        mypy --package feature_tracking || echo "MyPy completed with warnings"
    
    - name: Code analysis with Pylint
      run: |
        pylint ai_tools/ || echo "Pylint completed with warnings"
        pylint crew/ || echo "Pylint completed with warnings"
        pylint sysmon/ || echo "Pylint completed with warnings"
        pylint config_editor/ || echo "Pylint completed with warnings"
        pylint feature_tracking/ || echo "Pylint completed with warnings"