name: Release Management

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
      draft:
        description: 'Create as draft release'
        type: boolean
        default: false
      prerelease:
        description: 'Mark as prerelease'
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
    
    - name: Build packages
      run: |
        python -m build
    
    - name: Verify packages
      run: |
        ls -la dist/
        python -m twine check dist/*
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: CloudCurio ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
        body_path: RELEASE_NOTES.md
        draft: ${{ github.event.inputs.draft || false }}
        prerelease: ${{ github.event.inputs.prerelease || false }}
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: release-assets-${{ steps.version.outputs.version }}
        path: dist/*

  publish-pypi:
    runs-on: ubuntu-latest
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/project/cloudcurio/
    
    permissions:
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build packages
      run: |
        python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          cbwinslow/cloudcurio-mcp
          cbwinslow/cloudcurio-config-editor
        tags: |
          type=ref,event=tag
          type=raw,value=latest
    
    - name: Build and push MCP Server
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.mcp
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          cbwinslow/cloudcurio-mcp:${{ github.ref_name }}
          cbwinslow/cloudcurio-mcp:latest
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Build and push Config Editor
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.config-editor
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          cbwinslow/cloudcurio-config-editor:${{ github.ref_name }}
          cbwinslow/cloudcurio-config-editor:latest
        labels: ${{ steps.meta.outputs.labels }}