name: Run Tests on PR
on:
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run type checking
        run: pnpm lint
      - name: Run tests
        run: pnpm test