name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit security scan
      run: |
        bandit -r . -f json -o bandit-report.json || echo "Bandit scan completed"
    
    - name: Run Safety dependency scan
      run: |
        # Scan all requirements files
        find . -name "requirements.txt" -exec safety check -r {} --json \; > safety-report.json || echo "Safety scan completed"
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
    
    - name: Check for critical vulnerabilities
      run: |
        # Check Bandit report for HIGH severity issues
        if [ -f bandit-report.json ]; then
          high_issues=$(jq '.results | map(select(.issue_severity == "HIGH")) | length' bandit-report.json)
          if [ "$high_issues" -gt 0 ]; then
            echo "❌ Found $high_issues HIGH severity security issues in Bandit scan"
            jq '.results | map(select(.issue_severity == "HIGH"))' bandit-report.json
            exit 1
          else
            echo "✅ No HIGH severity issues found in Bandit scan"
          fi
        fi

  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install safety
      run: |
        pip install safety
    
    - name: Run dependency vulnerability scan
      run: |
        # Scan all requirements files for vulnerabilities
        find . -name "requirements.txt" -exec echo "Scanning {}" \; -exec safety check -r {} \;